server:
  port: 8080

#logging:
#  path: classpath:log4j2.yml

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: config-server
          uri: lb://config-server
          order: 9000
          predicates:
            - Path=/api-config/**
          filters:
            - StripPrefix=1
        - id: auth-server
          uri: lb://auth-server
          order: 9001
          predicates:
            - Path=/api-auth/**
          filters:
            - StripPrefix=1
        - id: user-server
          uri: lb://user-server
          order: 9002
          predicates:
            - Path=/api-user/**
          filters:
            - StripPrefix=1
            - Swagger2HeaderFilter



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    home-page-url-path: /
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

gateway:
  ignore:
    startWith: /auth/token,/user/account/register,/v2/api-docs