server:
  port: 9001
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000
spring: 
  application:
    name: gateway-service
  cloud: 
    gateway: 
      discovery: 
        locator:
          enabled: true
eureka: 
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    home-page-url-path: /
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
